package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/jmurray2011/cob/internal/cob"
	"github.com/jmurray2011/cob/internal/manifest"
)

func newInitCmd(cfg *Config) *cobra.Command {
	var flagMinimal bool

	cmd := &cobra.Command{
		Use:   "init [coordinates]",
		Short: "Print a starter manifest to stdout",
		Long: "Writes a cob manifest with placeholder values and inline " +
			"examples for each source type. Redirect to a file to save it. " +
			"The coordinates argument fills in any of " +
			"domain/repository/namespace/package; unspecified fields get " +
			"placeholders that pass `cob validate` so you can iterate. No " +
			"AWS calls.",
		Example: `  # generic placeholder template
  cob init > my-package.yaml

  # fill in the identifiers up front
  cob init acme/dev/tools/my-app > my-package.yaml

  # partial: only domain/repo, keep ns/pkg placeholders
  cob init acme/dev > my-package.yaml

  # bare schema (no comments, no promote stages)
  cob init acme/dev/tools/my-app --minimal > my-package.yaml`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			target := ""
			if len(args) > 0 {
				target = args[0]
			}
			return runInit(cfg, target, flagMinimal)
		},
	}
	cmd.Flags().BoolVar(&flagMinimal, "minimal", false, "Omit comments and the promote section")
	return cmd
}

func runInit(cfg *Config, target string, minimal bool) error {
	out := newWriter(cfg)
	defer out.Close()

	// Placeholders chosen so the generated manifest passes `cob validate`
	// out of the box — operators can iterate without first having to
	// invent valid-looking strings.
	coords := &cob.PackageCoordinates{
		Domain:     "my-domain",
		Repository: "dev",
		Namespace:  "my-namespace",
		Package:    "my-package",
	}
	if target != "" {
		parsed, err := manifest.ParseCoordinates(target)
		if err != nil {
			return fail(out, "init", cob.ExitError, "%s", err)
		}
		// Partial coords (just domain, or domain/repo) override only the
		// fields actually given; the rest keep their placeholders.
		if parsed.Domain != "" {
			coords.Domain = parsed.Domain
		}
		if parsed.Repository != "" {
			coords.Repository = parsed.Repository
		}
		if parsed.Namespace != "" {
			coords.Namespace = parsed.Namespace
		}
		if parsed.Package != "" {
			coords.Package = parsed.Package
		}
		if parsed.Version != "" {
			// @version in the init target has no semantic place in the
			// generated manifest (publishes pick a version via flag/env);
			// surface the misuse rather than silently dropping it.
			return fail(out, "init", cob.ExitError,
				"init does not accept an @version segment — the version is supplied at publish time")
		}
	}

	tpl := starterManifestTemplate
	if minimal {
		tpl = minimalManifestTemplate
	}
	fmt.Fprintf(out.Stdout(), tpl, coords.Domain, coords.Repository, coords.Namespace, coords.Package)
	return nil
}

const starterManifestTemplate = `# cob package manifest — generated by 'cob init'.
# Run 'cob validate <this-file>' for schema feedback as you edit.

domain: %s
repository: %s
namespace: %s
package: %s

sources:
  # Each entry is a source URI keyed by its manifest key. The stored asset
  # name is the URI's basename. ${VERSION} expands to --version /
  # COB_VERSION at publish time.
  #
  # Local file:
  #   my-binary: ./build/my-binary
  # S3 (upload with --checksum-algorithm SHA256 for a no-download verify):
  #   data.tar.gz: s3://my-bucket/builds/${VERSION}/data.tar.gz
  # Another cob package (recommended: pin with an explicit @version):
  #   shared-lib: ca://my-domain/dev/libs/shared-lib@1.4.0/shared-lib.tar.gz
  README.md: ./README.md

# Promotion ordering (optional). Drives 'cob promote <pkg.yaml> --to <stage>'.
promote:
  stages:
    - dev
    - staging
    - prod
`

const minimalManifestTemplate = `domain: %s
repository: %s
namespace: %s
package: %s

sources:
  README.md: ./README.md
`
